### ISSUE TITLE
Filtering of CTAs based on origin_system

### ISSUE THREAD

**Issue by AaronSofaer** [RagtagOpen/cta-aggregator#60]
Both yes ("give me only these") and no ("don't give me these")

**Comment by chrisbrickey** [comment]
I got this one!

**Comment by chrisbrickey** [comment]
Per conversation with Aaron, adjusting scope to only include yes/positive filters ("give me only these"). Excluding no/negative filters ("don't give me these") due to lack of documentation for such filters when using jsonapi-resources gem. Negative filters would require more work than is warranted by the priority of such a feature.

**Comment by AaronSofaer** [comment]
Delighted to see the PR! Let's leave the ticket open until both the filter is merged and the documentation is updated, because we do all of the work-tracking in this repo's Issues.

**Comment by bnd5k** [comment]
API PR: https://github.com/RagtagOpen/cta-aggregator/pull/106
Documentation PR: https://github.com/RagtagOpen/cta-aggregator-docs/pull/21
